export { SimpleEventEmitter } from './EventEmitter';
export type { EventEmitterLike } from './EventEmitter';
export { Damageable } from './Damageable';
export type { DamageableOptions, DamagedPayload } from './Damageable';
export { Targetable, CATEGORY_TARGET_PRIORITY } from './Targetable';
export type { TargetableOptions } from './Targetable';
export { Breakable } from './Breakable';
export type { BreakableOptions, DamageState } from './Breakable';
export { Upgradeable } from './Upgradeable';
export type { UpgradeableOptions, UpgradeOption } from './Upgradeable';
